export const INDIAN_CITIES = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur",
  "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara",
  "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi",
  "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur",
  "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh", "Solapur", "Hubli-Dharwad",
  "Bareilly", "Moradabad", "Mysore", "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar", "Salem", "Mira-Bhayandar",
  "Warangal", "Guntur", "Bhiwandi", "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida", "Jamshedpur", "Bhilai",
  "Cuttack", "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun", "Durgapur", "Asansol", "Rourkela", "Nanded",
  "Kolhapur", "Ajmer", "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar", "Nellore",
  "Jammu", "Sangli-Miraj & Kupwad", "Belgaum", "Mangalore", "Ambattur", "Tirunelveli", "Malegaon", "Gaya", "Jalgaon", "Udaipur",
  "Maheshtala", "Tirupur", "Davanagere", "Kozhikode", "Akola", "Kurnool", "Rajpur Sonarpur", "Rajahmundry", "Bokaro", "South Dumdum",
  "Bellary", "Patiala", "Gopalpur", "Agartala", "Bhagalpur", "Muzaffarnagar", "Bhatpara", "Panihati", "Latur", "Dhule",
  "Rohtak", "Korba", "Bhilwara", "Brahmapur", "Muzaffarpur", "Ahmednagar", "Mathura", "Kollam", "Avadi", "Rajahmundry",
  "Kadapa", "Kamarhati", "Bilaspur", "Shahjahanpur", "Bijapur", "Rampur", "Shivamogga", "Chandrapur", "Junagadh", "Thrissur",
  "Alwar", "Bardhaman", "Kulti", "Kakinada", "Nizamabad", "Parbhani", "Tumkur", "Khammam", "Uzhavarkarai", "Bihar Sharif",
  "Panipat", "Darbhanga", "Bally", "Aizawl", "Dewas", "Ichalkaranji", "Karnal", "Bathinda", "Jalna", "Eluru",
  "Barasat", "Kirari Suleman Nagar", "Purnia", "Satna", "Mau", "Sonipat", "Farrukhabad", "Sagar", "Rourkela", "Durg",
  "Imphal", "Ratlam", "Hapur", "Anantapur", "Arrah", "Karimnagar", "Ramagundam", "Etawah", "Ambernath", "Bharatpur",
  "Begusarai", "New Delhi", "Gandhidham", "Baranagar", "Tiruvottiyur", "Puducherry", "Sikar", "Thoothukudi", "Rewa", "Mirzapur",
  "Raichur", "Pali", "Ramagundam", "Haridwar", "Vijayanagaram", "Katihar", "Nagercoil", "Sri Ganganagar", "Karur", "Mango",
  "Thanjavur", "Bulandshahr", "Uluberia", "Murwara", "Sambhal", "Singrauli", "Nadiad", "Secunderabad", "Naihati", "Yamunanagar",
  "Bidhan Nagar", "Pallavaram", "Bidar", "Munger", "Panchkula", "Burhanpur", "Raurkela Industrial Township", "Kharagpur", "Dindigul", "Gandhinagar",
  "Hospet", "Nangloi Jat", "Malda", "Ongole", "Deoghar", "Chapra", "Haldia", "Khandwa", "Nandyal", "Morena",
  "Amroha", "Anand", "Bhind", "Bhalswa Jahangir Pur", "Madhyamgram", "Bhiwani", "Navi Mumbai Panvel Raigad", "Baharampur", "Ambala", "Morbi",
  "Fatehpur", "Rae Bareli", "Khorsha", "Budaun", "Bhimavaram", "Mahesana", "Sultan Pur Majra", "Raiganj", "Sirsa", "Danapur",
  "Buranpur", "Vidisha", "Khardah", "Kukatpally", "Karawal Nagar", "Bidar", "Hazaribagh", "Rishra", "Rewari", "Tinsukia",
  "Adityapur", "Alappuzha", "Kottayam", "Palakkad", "Manjeri", "Thalassery", "Ponnani", "Vatakara", "Kanhangad", "Taliparamba",
  "Koyilandy", "Neyyattinkara", "Kayamkulam", "Chittur-Thathamangalam", "Nedumangad", "Kannur", "Kasargod", "Malappuram", "Kozhikode", "Palghat",
  "Guruvayur", "Kochi", "Trivandrum", "Shimla", "Mandi", "Dharamsala", "Solan", "Bilaspur", "Chamba", "Hamirpur",
  "Una", "Kullu", "Paonta Sahib", "Sundarnagar", "Nahan", "Keylong", "Reckong Peo", "Kalpa", "Sarahan", "Manali",
  "Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Singtam", "Jorethang", "Nayabazar", "Pelling", "Ravangla",
  "Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Aalo", "Tezu", "Roing", "Khonsa",
  "Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Phek", "Mon", "Kiphire", "Longleng",
  "Shillong", "Tura", "Jowai", "Nongpoh", "Williamnagar", "Baghmara", "Resubelpara", "Mairang", "Khliehriat", "Mawkyrwat",
  "Agartala", "Dharmanagar", "Kailasahar", "Udaipur", "Ambassa", "Belonia", "Khowai", "Bishalgarh", "Santirbazar", "Teliamura",
  "Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim", "Curchorem", "Cuncolim", "Valpoi", "Sanquelim",
  "Silvassa", "Daman", "Diu", "Kavaratti", "Port Blair", "Diglipur", "Mayabunder", "Rangat", "Havelock Island", "Car Nicobar",
  "Chandigarh", "Panchkula", "Mohali", "Zirakpur", "Kharar", "Dera Bassi", "Pinjore", "Kalka", "Baddi", "Nalagarh",
  "Ludhiana", "Patiala", "Amritsar", "Jalandhar", "Bathinda", "Hoshiarpur", "Pathankot", "Moga", "Abohar", "Malerkotla",
  "Khanna", "Phagwara", "Muktsar", "Barnala", "Rajpura", "Firozpur", "Kapurthala", "Sangrur", "Batala", "Fazilka"
].sort();

export const CITY_OPTIONS = INDIAN_CITIES.map(city => ({
  label: city,
  value: city
}));
