'use client';

import { useState, useEffect } from 'react';
import {
  Users, Phone, MapPin, GraduationCap,
  User, Calendar, Building2, Home,
  FileText, Search, X, RefreshCw, ChevronDown,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import {
  Table, TableBody, TableCell, TableHead,
  TableHeader, TableRow,
} from '@/components/ui/table';

interface PmsLead {
  _id: string;
  parentName: string;
  studentName: string;
  phone: string;
  city: string;
  studentCity?: string;
  studentState?: string;
  grade: string;
  schoolInterested?: string;
  schoolType?: string;
  status: 'new' | 'contacted' | 'converted' | 'rejected';
  earnings: number;
  notes?: string;
  createdAt: string;
  freelancer: { name: string; email: string; phone?: string } | null;
}

const STATUS_CONFIG: Record<string, { label: string; class: string }> = {
  new:       { label: 'New',       class: 'bg-blue-50 text-blue-700 border border-blue-200' },
  contacted: { label: 'Contacted', class: 'bg-amber-50 text-amber-700 border border-amber-200' },
  converted: { label: 'Converted', class: 'bg-emerald-50 text-emerald-700 border border-emerald-200' },
  rejected:  { label: 'Rejected',  class: 'bg-red-50 text-red-700 border border-red-200' },
};

export function PMSLeadSection() {
  const [leads, setLeads] = useState<PmsLead[]>([]);
  const [filtered, setFiltered] = useState<PmsLead[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'new' | 'contacted' | 'converted' | 'rejected'>('all');
  const [schoolName, setSchoolName] = useState('');
  const [updatingId, setUpdatingId] = useState<string | null>(null);

  const fetchLeads = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/schools/pms-leads', {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) throw new Error('Failed to fetch');
      const data = await res.json();
      setLeads(data.leads || []);
      setFiltered(data.leads || []);
      setSchoolName(data.schoolName || '');
    } catch (e) {
      console.error('Failed to fetch PMS leads:', e);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (leadId: string, newStatus: PmsLead['status']) => {
    const token = localStorage.getItem('token');
    if (!token || updatingId) return;
    setUpdatingId(leadId);
    try {
      const res = await fetch('/api/schools/pms-leads', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ leadId, status: newStatus }),
      });
      const data = await res.json();
      if (res.ok) {
        setLeads(prev => prev.map(l => l._id === leadId ? { ...l, status: newStatus } : l));
        toast.success(`Status updated to ${STATUS_CONFIG[newStatus].label}`);
      } else {
        toast.error(data.error || 'Failed to update status');
      }
    } catch {
      toast.error('Failed to update status');
    } finally {
      setUpdatingId(null);
    }
  };

  useEffect(() => { fetchLeads(); }, []);

  useEffect(() => {
    let result = leads;
    if (statusFilter !== 'all') result = result.filter(l => l.status === statusFilter);
    if (query.trim()) {
      const q = query.toLowerCase();
      result = result.filter(l =>
        l.studentName.toLowerCase().includes(q) ||
        l.parentName.toLowerCase().includes(q) ||
        l.phone.includes(q) ||
        (l.studentCity || l.city || '').toLowerCase().includes(q) ||
        (l.freelancer?.name || '').toLowerCase().includes(q)
      );
    }
    setFiltered(result);
  }, [query, statusFilter, leads]);

  const countFor = (s: string) => s === 'all' ? leads.length : leads.filter(l => l.status === s).length;

  const fmt = (d: string) =>
    new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shrink-0">
              <Users className="w-4 h-4 text-white" />
            </span>
            PMS Leads
          </h2>
          <p className="text-slate-500 mt-1 text-sm">
            Leads generated by PickMySchool freelancers{schoolName ? ` for ${schoolName}` : ''}
          </p>
        </div>
        <button
          onClick={fetchLeads}
          className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 text-sm font-medium transition-colors"
        >
          <RefreshCw className="w-4 h-4" />
          Refresh
        </button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {(['new', 'contacted', 'converted', 'rejected'] as const).map(s => (
          <button
            key={s}
            onClick={() => setStatusFilter(s)}
            className={`text-left p-3 rounded-xl border-2 transition-all ${
              statusFilter === s ? 'ring-2 ring-emerald-500 ring-offset-1' : ''
            } ${STATUS_CONFIG[s].class}`}
          >
            <p className="text-xs font-medium opacity-70">{STATUS_CONFIG[s].label}</p>
            <p className="text-2xl font-bold mt-0.5">{countFor(s)}</p>
          </button>
        ))}
      </div>

      {/* Filters row */}
      <div className="flex flex-wrap items-center gap-3">
        {/* Search */}
        <div className="relative flex-1 min-w-[200px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none" />
          <Input
            value={query}
            onChange={e => setQuery(e.target.value)}
            placeholder="Search student, parent, phone, city, freelancer..."
            className="h-9 pl-9 pr-9 bg-white"
          />
          {query && (
            <button onClick={() => setQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600">
              <X className="w-4 h-4" />
            </button>
          )}
        </div>

        {/* Status pills */}
        <div className="flex flex-wrap gap-1.5">
          {(['all', 'new', 'contacted', 'converted', 'rejected'] as const).map(s => (
            <button
              key={s}
              onClick={() => setStatusFilter(s)}
              className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors border ${
                statusFilter === s
                  ? 'bg-emerald-600 text-white border-emerald-600'
                  : 'bg-white text-slate-600 border-slate-200 hover:border-emerald-400'
              }`}
            >
              {s === 'all' ? 'All' : STATUS_CONFIG[s].label}
              <span className="ml-1 opacity-70">({countFor(s)})</span>
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      {loading ? (
        <Card className="border-0 shadow-md overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  {['#', 'Student', 'Parent', 'Phone', 'City / State', 'Grade', 'School Type', 'Status', 'Date', 'Notes'].map(h => (
                    <th key={h} className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {Array.from({ length: 5 }).map((_, i) => (
                  <tr key={i} className="animate-pulse">
                    {Array.from({ length: 10 }).map((_, j) => (
                      <td key={j} className="px-4 py-3"><div className="h-4 bg-slate-100 rounded w-20" /></td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      ) : filtered.length === 0 ? (
        <Card className="border-0 shadow-md">
          <CardContent className="p-14 text-center">
            <Users className="w-12 h-12 text-slate-200 mx-auto mb-3" />
            <p className="text-slate-500 font-medium">No PMS leads found</p>
            <p className="text-sm text-slate-400 mt-1">
              {leads.length === 0
                ? 'No freelancer leads have been generated for your school yet'
                : 'No leads match your current filters'}
            </p>
          </CardContent>
        </Card>
      ) : (
        <Card className="border-0 shadow-md overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">#</th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><User className="w-3.5 h-3.5" />Student</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><User className="w-3.5 h-3.5" />Parent</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><Phone className="w-3.5 h-3.5" />Phone</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><MapPin className="w-3.5 h-3.5" />City / State</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><GraduationCap className="w-3.5 h-3.5" />Grade</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><Building2 className="w-3.5 h-3.5" />School Type</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">Status</th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><Calendar className="w-3.5 h-3.5" />Date</span>
                  </th>
                  <th className="text-left px-4 py-3 font-semibold text-slate-500 text-xs whitespace-nowrap">
                    <span className="flex items-center gap-1.5"><FileText className="w-3.5 h-3.5" />Notes</span>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filtered.map((lead, idx) => {
                  const cityDisplay = [lead.studentCity || lead.city, lead.studentState].filter(Boolean).join(', ') || '—';
                  const isHostel = lead.schoolType?.toLowerCase().includes('hostel');
                  return (
                    <tr key={lead._id} className="hover:bg-slate-50 transition-colors">
                      <td className="px-4 py-3 text-slate-400 text-xs">{idx + 1}</td>

                      <td className="px-4 py-3">
                        <p className="font-semibold text-slate-800 whitespace-nowrap">{lead.studentName}</p>
                      </td>

                      <td className="px-4 py-3">
                        <p className="text-slate-600 whitespace-nowrap">{lead.parentName}</p>
                      </td>

                      <td className="px-4 py-3">
                        <a href={`tel:${lead.phone}`} className="text-slate-600 hover:text-emerald-600 whitespace-nowrap font-mono text-xs">
                          {lead.phone}
                        </a>
                      </td>

                      <td className="px-4 py-3">
                        <span className="text-slate-600 text-xs whitespace-nowrap">{cityDisplay}</span>
                      </td>

                      <td className="px-4 py-3">
                        <span className="inline-block px-2 py-0.5 bg-slate-100 text-slate-600 rounded text-xs font-medium whitespace-nowrap">
                          {lead.grade || '—'}
                        </span>
                      </td>

                      <td className="px-4 py-3">
                        {lead.schoolType ? (
                          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium whitespace-nowrap ${
                            isHostel
                              ? 'bg-purple-50 text-purple-700 border border-purple-100'
                              : 'bg-blue-50 text-blue-700 border border-blue-100'
                          }`}>
                            {isHostel ? <Home className="w-3 h-3" /> : <Building2 className="w-3 h-3" />}
                            {lead.schoolType}
                          </span>
                        ) : (
                          <span className="text-slate-300 text-xs">—</span>
                        )}
                      </td>

                      <td className="px-4 py-3">
                        <div className="relative inline-block">
                          <select
                            value={lead.status}
                            disabled={updatingId === lead._id}
                            onChange={e => updateStatus(lead._id, e.target.value as PmsLead['status'])}
                            className={`appearance-none pl-2.5 pr-7 py-0.5 rounded-full text-xs font-semibold border cursor-pointer focus:outline-none transition-opacity ${
                              updatingId === lead._id ? 'opacity-50 cursor-wait' : ''
                            } ${STATUS_CONFIG[lead.status]?.class || ''}`}
                          >
                            <option value="new">New</option>
                            <option value="contacted">Contacted</option>
                            <option value="converted">Converted</option>
                            <option value="rejected">Rejected</option>
                          </select>
                          <ChevronDown className="absolute right-1.5 top-1/2 -translate-y-1/2 w-3 h-3 pointer-events-none opacity-60" />
                        </div>
                      </td>

                      <td className="px-4 py-3">
                        <span className="text-slate-500 text-xs whitespace-nowrap">{fmt(lead.createdAt)}</span>
                      </td>

                      <td className="px-4 py-3 max-w-[160px]">
                        {lead.notes ? (
                          <p className="text-slate-400 text-xs italic line-clamp-2" title={lead.notes}>{lead.notes}</p>
                        ) : (
                          <span className="text-slate-300 text-xs">—</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Footer */}
          <div className="px-4 py-3 border-t border-slate-100 bg-slate-50 flex items-center justify-between text-xs text-slate-400">
            <span>Showing {filtered.length} of {leads.length} leads</span>
            {leads.filter(l => l.status === 'converted').length > 0 && (
              <span className="text-emerald-600 font-medium">
                Converted: {leads.filter(l => l.status === 'converted').length} leads
              </span>
            )}
          </div>
        </Card>
      )}
    </div>
  );
}
