import { sqliteTable, AnySQLiteColumn, foreignKey, integer, text, real, uniqueIndex } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const chats = sqliteTable("chats", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	userId: integer("user_id").notNull().references(() => users.id),
	role: text().notNull(),
	messages: text(),
	lastMessageAt: text("last_message_at"),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const enquiries = sqliteTable("enquiries", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	studentId: integer("student_id").notNull().references(() => users.id),
	schoolId: integer("school_id").notNull().references(() => schools.id),
	studentName: text("student_name").notNull(),
	studentEmail: text("student_email").notNull(),
	studentPhone: text("student_phone").notNull(),
	studentClass: text("student_class").notNull(),
	message: text(),
	status: text().default("New").notNull(),
	notes: text(),
	followUpDate: text("follow_up_date"),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const schools = sqliteTable("schools", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	name: text().notNull(),
	logo: text(),
	bannerImage: text("banner_image"),
	address: text(),
	city: text().notNull(),
	state: text(),
	pincode: text(),
	board: text().notNull(),
	medium: text(),
	classesOffered: text("classes_offered"),
	establishmentYear: integer("establishment_year"),
	studentTeacherRatio: text("student_teacher_ratio"),
	schoolType: text("school_type"),
	feesMin: integer("fees_min"),
	feesMax: integer("fees_max"),
	facilities: text(),
	description: text(),
	gallery: text(),
	contactEmail: text("contact_email"),
	contactPhone: text("contact_phone"),
	rating: real(),
	reviewCount: integer("review_count").default(0),
	profileViews: integer("profile_views").default(0),
	featured: integer().default(false),
	latitude: real(),
	longitude: real(),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
	userId: integer("user_id").references(() => users.id),
	k12Level: text("k12_level"),
	gender: text(),
	isInternational: integer("is_international").default(false),
	streamsAvailable: text("streams_available"),
	languages: text(),
	totalStudents: text("total_students"),
	totalTeachers: integer("total_teachers"),
	logoUrl: text("logo_url"),
	country: text(),
	website: text(),
	contactNumber: text("contact_number"),
	whatsappNumber: text("whatsapp_number"),
	email: text(),
	facebookUrl: text("facebook_url"),
	instagramUrl: text("instagram_url"),
	linkedinUrl: text("linkedin_url"),
	youtubeUrl: text("youtube_url"),
	googleMapUrl: text("google_map_url"),
	classroomType: text("classroom_type"),
	hasLibrary: integer("has_library").default(false),
	hasComputerLab: integer("has_computer_lab").default(false),
	computerCount: integer("computer_count"),
	hasPhysicsLab: integer("has_physics_lab").default(false),
	hasChemistryLab: integer("has_chemistry_lab").default(false),
	hasBiologyLab: integer("has_biology_lab").default(false),
	hasMathsLab: integer("has_maths_lab").default(false),
	hasLanguageLab: integer("has_language_lab").default(false),
	hasRoboticsLab: integer("has_robotics_lab").default(false),
	hasStemLab: integer("has_stem_lab").default(false),
	hasAuditorium: integer("has_auditorium").default(false),
	hasPlayground: integer("has_playground").default(false),
	sportsFacilities: text("sports_facilities"),
	hasSwimmingPool: integer("has_swimming_pool").default(false),
	hasFitnessCentre: integer("has_fitness_centre").default(false),
	hasYoga: integer("has_yoga").default(false),
	hasMartialArts: integer("has_martial_arts").default(false),
	hasMusicDance: integer("has_music_dance").default(false),
	hasHorseRiding: integer("has_horse_riding").default(false),
	hasSmartBoard: integer("has_smart_board").default(false),
	hasWifi: integer("has_wifi").default(false),
	hasCctv: integer("has_cctv").default(false),
	hasElearning: integer("has_elearning").default(false),
	hasAcClassrooms: integer("has_ac_classrooms").default(false),
	hasAiTools: integer("has_ai_tools").default(false),
	hasTransport: integer("has_transport").default(false),
	hasGpsBuses: integer("has_gps_buses").default(false),
	hasCctvBuses: integer("has_cctv_buses").default(false),
	hasBusCaretaker: integer("has_bus_caretaker").default(false),
	hasMedicalRoom: integer("has_medical_room").default(false),
	hasDoctorNurse: integer("has_doctor_nurse").default(false),
	hasFireSafety: integer("has_fire_safety").default(false),
	hasCleanWater: integer("has_clean_water").default(false),
	hasSecurityGuards: integer("has_security_guards").default(false),
	hasAirPurifier: integer("has_air_purifier").default(false),
	hasHostel: integer("has_hostel").default(false),
	hasMess: integer("has_mess").default(false),
	hasHostelStudyRoom: integer("has_hostel_study_room").default(false),
	hasAcHostel: integer("has_ac_hostel").default(false),
	hasCafeteria: integer("has_cafeteria").default(false),
	galleryImages: text("gallery_images"),
	virtualTourUrl: text("virtual_tour_url"),
	prospectusUrl: text("prospectus_url"),
	awards: text(),
	newsletterUrl: text("newsletter_url"),
	feesStructure: text("fees_structure"),
	facilityImages: text("facility_images"),
	aboutSchool: text("about_school"),
	bannerImageUrl: text("banner_image_url"),
	virtualTourVideos: text("virtual_tour_videos"),
});

export const users = sqliteTable("users", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	role: text().notNull(),
	email: text().notNull(),
	password: text().notNull(),
	name: text().notNull(),
	phone: text(),
	city: text(),
	class: text(),
	schoolId: integer("school_id"),
	savedSchools: text("saved_schools"),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
},
(table) => [
	uniqueIndex("users_email_unique").on(table.email),
]);

export const siteSettings = sqliteTable("site_settings", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	spotlightSchoolId: integer("spotlight_school_id").references(() => schools.id),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const superAdmin = sqliteTable("super_admin", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	email: text().notNull(),
	password: text().notNull(),
	name: text().notNull(),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
},
(table) => [
	uniqueIndex("super_admin_email_unique").on(table.email),
]);

export const reviews = sqliteTable("reviews", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	userId: integer("user_id").notNull().references(() => users.id),
	schoolId: integer("school_id").notNull().references(() => schools.id),
	rating: integer().notNull(),
	reviewText: text("review_text").notNull(),
	photos: text(),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
	approvalStatus: text("approval_status").default("pending").notNull(),
});

export const testimonials = sqliteTable("testimonials", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	parentName: text("parent_name").notNull(),
	location: text().notNull(),
	rating: integer().notNull(),
	testimonialText: text("testimonial_text").notNull(),
	avatarUrl: text("avatar_url"),
	featured: integer().default(false),
	displayOrder: integer("display_order"),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const results = sqliteTable("results", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	schoolId: integer("school_id").notNull().references(() => schools.id),
	year: integer().notNull(),
	examType: text("exam_type").notNull(),
	classLevel: text("class_level"),
	passPercentage: real("pass_percentage"),
	totalStudents: integer("total_students"),
	distinction: integer(),
	firstClass: integer("first_class"),
	toppers: text(),
	achievements: text(),
	certificateImages: text("certificate_images"),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const alumni = sqliteTable("alumni", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	schoolId: integer("school_id").notNull().references(() => schools.id),
	name: text().notNull(),
	batchYear: integer("batch_year").notNull(),
	classLevel: text("class_level"),
	section: text(),
	currentPosition: text("current_position"),
	company: text(),
	achievements: text(),
	photoUrl: text("photo_url"),
	linkedinUrl: text("linkedin_url"),
	quote: text(),
	featured: integer().default(false),
	displayOrder: integer("display_order"),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const news = sqliteTable("news", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	schoolId: integer("school_id").notNull().references(() => schools.id),
	title: text().notNull(),
	content: text().notNull(),
	category: text().notNull(),
	publishDate: text("publish_date").notNull(),
	images: text(),
	isPublished: integer("is_published").default(true),
	featured: integer().default(false),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

