import { db } from '@/db';
import { schools } from '@/db/schema';

async function main() {
    const sampleSchools = [
        // Delhi Schools (6)
        {
            name: 'Delhi Public School, Vasant Kunj',
            logo: 'https://via.placeholder.com/150x150?text=DPS+VK',
            bannerImage: 'https://via.placeholder.com/1200x400?text=DPS+Vasant+Kunj+Banner',
            address: 'Sector C, Pocket VIII, Vasant Kunj',
            city: 'Delhi',
            state: 'Delhi',
            pincode: '110070',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 1985,
            studentTeacherRatio: '20:1',
            schoolType: 'Day School',
            feesMin: 45000,
            feesMax: 120000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Smart Classrooms', 'Cafeteria'],
            description: 'DPS Vasant Kunj is one of the premier CBSE schools in Delhi, known for its academic excellence and holistic development approach. The school has consistently produced outstanding results and nurtures students to become global citizens with strong values.',
            gallery: [
                'https://via.placeholder.com/800x600?text=DPS+VK+Campus+1',
                'https://via.placeholder.com/800x600?text=DPS+VK+Sports',
                'https://via.placeholder.com/800x600?text=DPS+VK+Library',
                'https://via.placeholder.com/800x600?text=DPS+VK+Labs',
                'https://via.placeholder.com/800x600?text=DPS+VK+Auditorium'
            ],
            contactEmail: 'admissions@dpsvasantkunj.edu.in',
            contactPhone: '+91-11-26897000',
            rating: 4.7,
            reviewCount: 320,
            profileViews: 4200,
            featured: true,
            latitude: 28.5355,
            longitude: 77.1617,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Modern School, Barakhamba Road',
            logo: 'https://via.placeholder.com/150x150?text=Modern+School',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Modern+School+Banner',
            address: 'Barakhamba Road, Connaught Place',
            city: 'Delhi',
            state: 'Delhi',
            pincode: '110001',
            board: 'CBSE',
            medium: 'English',
            classesOffered: '1st to 12th',
            establishmentYear: 1920,
            studentTeacherRatio: '18:1',
            schoolType: 'Day School',
            feesMin: 55000,
            feesMax: 150000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms'],
            description: 'Established in 1920, Modern School is one of Delhi\'s oldest and most prestigious institutions. With a rich legacy of academic excellence, the school focuses on character building and creating future leaders.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Modern+Campus+1',
                'https://via.placeholder.com/800x600?text=Modern+Building',
                'https://via.placeholder.com/800x600?text=Modern+Sports',
                'https://via.placeholder.com/800x600?text=Modern+Lab'
            ],
            contactEmail: 'info@modernschool.edu.in',
            contactPhone: '+91-11-23312691',
            rating: 4.8,
            reviewCount: 450,
            profileViews: 5000,
            featured: true,
            latitude: 28.6304,
            longitude: 77.2177,
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            name: 'Ryan International School, Rohini',
            logo: 'https://via.placeholder.com/150x150?text=Ryan+Rohini',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Ryan+Rohini+Banner',
            address: 'Sector 25, Rohini',
            city: 'Delhi',
            state: 'Delhi',
            pincode: '110085',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Pre-KG to 12th',
            establishmentYear: 1995,
            studentTeacherRatio: '25:1',
            schoolType: 'Day School',
            feesMin: 35000,
            feesMax: 90000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Cafeteria', 'Medical Room', 'Smart Classrooms'],
            description: 'Ryan International School Rohini provides quality education with emphasis on sports and extracurricular activities. The school believes in nurturing each child\'s unique potential through innovative teaching methods.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Ryan+Campus',
                'https://via.placeholder.com/800x600?text=Ryan+Playground',
                'https://via.placeholder.com/800x600?text=Ryan+Classroom',
                'https://via.placeholder.com/800x600?text=Ryan+Lab',
                'https://via.placeholder.com/800x600?text=Ryan+Sports'
            ],
            contactEmail: 'admissions@ryanrohini.edu.in',
            contactPhone: '+91-11-27552000',
            rating: 4.3,
            reviewCount: 180,
            profileViews: 2100,
            featured: false,
            latitude: 28.7466,
            longitude: 77.0668,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'St. Xavier\'s School, Raj Nagar',
            logo: 'https://via.placeholder.com/150x150?text=St+Xaviers',
            bannerImage: 'https://via.placeholder.com/1200x400?text=St+Xaviers+Banner',
            address: 'Raj Nagar Part-1, Palam Colony',
            city: 'Delhi',
            state: 'Delhi',
            pincode: '110077',
            board: 'ICSE',
            medium: 'English',
            classesOffered: 'KG to 12th',
            establishmentYear: 1960,
            studentTeacherRatio: '15:1',
            schoolType: 'Day School',
            feesMin: 60000,
            feesMax: 160000,
            facilities: ['Library', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Chapel', 'Smart Classrooms', 'Cafeteria'],
            description: 'St. Xavier\'s School is a premier ICSE institution committed to academic excellence and moral values. The school provides a nurturing environment where students develop into responsible global citizens.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Xavier+Building',
                'https://via.placeholder.com/800x600?text=Xavier+Chapel',
                'https://via.placeholder.com/800x600?text=Xavier+Sports',
                'https://via.placeholder.com/800x600?text=Xavier+Library'
            ],
            contactEmail: 'admissions@stxaviersdelhi.edu.in',
            contactPhone: '+91-11-25084000',
            rating: 4.6,
            reviewCount: 280,
            profileViews: 3400,
            featured: true,
            latitude: 28.5733,
            longitude: 77.1033,
            createdAt: new Date('2024-08-01').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            name: 'DAV Public School, Pushpanjali',
            logo: 'https://via.placeholder.com/150x150?text=DAV+Pushpanjali',
            bannerImage: 'https://via.placeholder.com/1200x400?text=DAV+Pushpanjali+Banner',
            address: 'Pushpanjali Enclave, Pitampura',
            city: 'Delhi',
            state: 'Delhi',
            pincode: '110088',
            board: 'CBSE',
            medium: 'English/Hindi',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 1988,
            studentTeacherRatio: '25:1',
            schoolType: 'Day School',
            feesMin: 25000,
            feesMax: 70000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Smart Classrooms', 'Medical Room'],
            description: 'DAV Pushpanjali focuses on providing quality education rooted in Indian values and culture. The school emphasizes both academic excellence and character development through its value-based education system.',
            gallery: [
                'https://via.placeholder.com/800x600?text=DAV+Campus',
                'https://via.placeholder.com/800x600?text=DAV+Classroom',
                'https://via.placeholder.com/800x600?text=DAV+Lab',
                'https://via.placeholder.com/800x600?text=DAV+Sports',
                'https://via.placeholder.com/800x600?text=DAV+Library'
            ],
            contactEmail: 'info@davpushpanjali.edu.in',
            contactPhone: '+91-11-27012000',
            rating: 4.2,
            reviewCount: 150,
            profileViews: 1800,
            featured: false,
            latitude: 28.7041,
            longitude: 77.1025,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'The Heritage School, Vasant Vihar',
            logo: 'https://via.placeholder.com/150x150?text=Heritage+School',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Heritage+School+Banner',
            address: 'Priya Complex, Vasant Vihar',
            city: 'Delhi',
            state: 'Delhi',
            pincode: '110057',
            board: 'IB',
            medium: 'English',
            classesOffered: 'Pre-KG to 12th',
            establishmentYear: 2005,
            studentTeacherRatio: '15:1',
            schoolType: 'Day School',
            feesMin: 80000,
            feesMax: 200000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Cafeteria', 'Design Lab'],
            description: 'The Heritage School offers the IB curriculum with a focus on international standards of education. The school encourages inquiry-based learning and prepares students for global challenges with its progressive approach.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Heritage+Building',
                'https://via.placeholder.com/800x600?text=Heritage+Lab',
                'https://via.placeholder.com/800x600?text=Heritage+Sports',
                'https://via.placeholder.com/800x600?text=Heritage+Pool',
                'https://via.placeholder.com/800x600?text=Heritage+Studio'
            ],
            contactEmail: 'admissions@heritageschool.edu.in',
            contactPhone: '+91-11-26141234',
            rating: 4.9,
            reviewCount: 220,
            profileViews: 3800,
            featured: true,
            latitude: 28.5494,
            longitude: 77.1642,
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        // Mumbai Schools (5)
        {
            name: 'Delhi Public School, Navi Mumbai',
            logo: 'https://via.placeholder.com/150x150?text=DPS+Mumbai',
            bannerImage: 'https://via.placeholder.com/1200x400?text=DPS+Navi+Mumbai+Banner',
            address: 'Sector 10, Nerul East, Navi Mumbai',
            city: 'Mumbai',
            state: 'Maharashtra',
            pincode: '400706',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 1998,
            studentTeacherRatio: '20:1',
            schoolType: 'Day School',
            feesMin: 50000,
            feesMax: 130000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Smart Classrooms', 'Cafeteria', 'Medical Room'],
            description: 'DPS Navi Mumbai is committed to providing world-class education with state-of-the-art facilities. The school focuses on holistic development and has established itself as one of the leading educational institutions in Mumbai.',
            gallery: [
                'https://via.placeholder.com/800x600?text=DPS+Mumbai+Campus',
                'https://via.placeholder.com/800x600?text=DPS+Mumbai+Building',
                'https://via.placeholder.com/800x600?text=DPS+Mumbai+Sports',
                'https://via.placeholder.com/800x600?text=DPS+Mumbai+Lab',
                'https://via.placeholder.com/800x600?text=DPS+Mumbai+Pool'
            ],
            contactEmail: 'admissions@dpsmumbai.edu.in',
            contactPhone: '+91-22-27712000',
            rating: 4.6,
            reviewCount: 340,
            profileViews: 4100,
            featured: true,
            latitude: 19.0330,
            longitude: 73.0297,
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            name: 'Podar International School, Powai',
            logo: 'https://via.placeholder.com/150x150?text=Podar+Powai',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Podar+Powai+Banner',
            address: 'Hiranandani Gardens, Powai',
            city: 'Mumbai',
            state: 'Maharashtra',
            pincode: '400076',
            board: 'ICSE',
            medium: 'English',
            classesOffered: 'KG to 12th',
            establishmentYear: 2010,
            studentTeacherRatio: '18:1',
            schoolType: 'Day School',
            feesMin: 55000,
            feesMax: 145000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Robotics Lab'],
            description: 'Podar International School Powai provides a nurturing environment with focus on innovative pedagogy. The school is known for its strong academic curriculum combined with extensive co-curricular opportunities.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Podar+Campus',
                'https://via.placeholder.com/800x600?text=Podar+Classroom',
                'https://via.placeholder.com/800x600?text=Podar+Lab',
                'https://via.placeholder.com/800x600?text=Podar+Sports'
            ],
            contactEmail: 'admissions@podarpowai.edu.in',
            contactPhone: '+91-22-25701234',
            rating: 4.5,
            reviewCount: 260,
            profileViews: 3200,
            featured: false,
            latitude: 19.1197,
            longitude: 72.9080,
            createdAt: new Date('2024-09-01').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            name: 'Bombay Scottish School, Mahim',
            logo: 'https://via.placeholder.com/150x150?text=Bombay+Scottish',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Bombay+Scottish+Banner',
            address: 'Veer Savarkar Marg, Mahim',
            city: 'Mumbai',
            state: 'Maharashtra',
            pincode: '400016',
            board: 'ICSE',
            medium: 'English',
            classesOffered: '1st to 12th',
            establishmentYear: 1847,
            studentTeacherRatio: '15:1',
            schoolType: 'Day School',
            feesMin: 65000,
            feesMax: 170000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Smart Classrooms', 'Cafeteria'],
            description: 'One of Mumbai\'s oldest and most prestigious schools, Bombay Scottish has a rich heritage of academic excellence. The school maintains high standards in both academics and character development.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Scottish+Building',
                'https://via.placeholder.com/800x600?text=Scottish+Heritage',
                'https://via.placeholder.com/800x600?text=Scottish+Campus',
                'https://via.placeholder.com/800x600?text=Scottish+Library',
                'https://via.placeholder.com/800x600?text=Scottish+Sports'
            ],
            contactEmail: 'info@bombayscottish.edu.in',
            contactPhone: '+91-22-24451275',
            rating: 4.8,
            reviewCount: 420,
            profileViews: 4800,
            featured: true,
            latitude: 19.0403,
            longitude: 72.8424,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Ryan International School, Kandivali',
            logo: 'https://via.placeholder.com/150x150?text=Ryan+Kandivali',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Ryan+Kandivali+Banner',
            address: 'Thakur Complex, Kandivali East',
            city: 'Mumbai',
            state: 'Maharashtra',
            pincode: '400101',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 2000,
            studentTeacherRatio: '25:1',
            schoolType: 'Day School',
            feesMin: 40000,
            feesMax: 100000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Smart Classrooms', 'Cafeteria', 'Medical Room'],
            description: 'Ryan International Kandivali provides comprehensive education with emphasis on both academics and sports. The school creates a balanced environment for students to excel in all areas of development.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Ryan+Kandivali+Campus',
                'https://via.placeholder.com/800x600?text=Ryan+Kandivali+Sports',
                'https://via.placeholder.com/800x600?text=Ryan+Kandivali+Lab',
                'https://via.placeholder.com/800x600?text=Ryan+Kandivali+Class'
            ],
            contactEmail: 'admissions@ryankandivali.edu.in',
            contactPhone: '+91-22-28681234',
            rating: 4.2,
            reviewCount: 175,
            profileViews: 2400,
            featured: false,
            latitude: 19.2028,
            longitude: 72.8478,
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            name: 'Dhirubhai Ambani International School',
            logo: 'https://via.placeholder.com/150x150?text=DAIS',
            bannerImage: 'https://via.placeholder.com/1200x400?text=DAIS+Banner',
            address: 'Bandra Kurla Complex, Bandra East',
            city: 'Mumbai',
            state: 'Maharashtra',
            pincode: '400051',
            board: 'IB',
            medium: 'English',
            classesOffered: 'Pre-KG to 12th',
            establishmentYear: 2003,
            studentTeacherRatio: '15:1',
            schoolType: 'Day School',
            feesMin: 75000,
            feesMax: 180000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Cafeteria', 'Innovation Lab', 'Design Studio'],
            description: 'DAIS is a world-class IB school offering exceptional educational facilities and programs. The school focuses on developing global citizens with strong leadership skills and social responsibility.',
            gallery: [
                'https://via.placeholder.com/800x600?text=DAIS+Campus',
                'https://via.placeholder.com/800x600?text=DAIS+Building',
                'https://via.placeholder.com/800x600?text=DAIS+Lab',
                'https://via.placeholder.com/800x600?text=DAIS+Sports',
                'https://via.placeholder.com/800x600?text=DAIS+Pool',
                'https://via.placeholder.com/800x600?text=DAIS+Library'
            ],
            contactEmail: 'admissions@dais.edu.in',
            contactPhone: '+91-22-66285000',
            rating: 4.9,
            reviewCount: 380,
            profileViews: 4600,
            featured: true,
            latitude: 19.0596,
            longitude: 72.8656,
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        // Bangalore Schools (4)
        {
            name: 'Greenwood High International School',
            logo: 'https://via.placeholder.com/150x150?text=Greenwood',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Greenwood+Banner',
            address: 'Devarabeesanahalli, Sarjapur Road',
            city: 'Bangalore',
            state: 'Karnataka',
            pincode: '560103',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 2008,
            studentTeacherRatio: '18:1',
            schoolType: 'Day School',
            feesMin: 60000,
            feesMax: 155000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Innovation Lab'],
            description: 'Greenwood High is renowned for its progressive teaching methodologies and excellent infrastructure. The school provides a stimulating environment that encourages students to think critically and creatively.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Greenwood+Campus',
                'https://via.placeholder.com/800x600?text=Greenwood+Building',
                'https://via.placeholder.com/800x600?text=Greenwood+Sports',
                'https://via.placeholder.com/800x600?text=Greenwood+Lab',
                'https://via.placeholder.com/800x600?text=Greenwood+Pool'
            ],
            contactEmail: 'admissions@greenwoodhigh.edu.in',
            contactPhone: '+91-80-42504000',
            rating: 4.7,
            reviewCount: 295,
            profileViews: 3700,
            featured: false,
            latitude: 12.9121,
            longitude: 77.6896,
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            name: 'Bishop Cotton Boys\' School',
            logo: 'https://via.placeholder.com/150x150?text=Bishop+Cotton',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Bishop+Cotton+Banner',
            address: 'St. Mark\'s Road',
            city: 'Bangalore',
            state: 'Karnataka',
            pincode: '560001',
            board: 'ICSE',
            medium: 'English',
            classesOffered: '1st to 12th',
            establishmentYear: 1865,
            studentTeacherRatio: '15:1',
            schoolType: 'Boarding',
            feesMin: 70000,
            feesMax: 175000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Hostel', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Chapel', 'Medical Room'],
            description: 'Bishop Cotton is one of India\'s oldest and most prestigious boys\' boarding schools. With a legacy of over 150 years, the school is known for its emphasis on discipline, character, and academic excellence.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Bishop+Heritage',
                'https://via.placeholder.com/800x600?text=Bishop+Campus',
                'https://via.placeholder.com/800x600?text=Bishop+Sports',
                'https://via.placeholder.com/800x600?text=Bishop+Chapel',
                'https://via.placeholder.com/800x600?text=Bishop+Hostel'
            ],
            contactEmail: 'admissions@bishopcotton.edu.in',
            contactPhone: '+91-80-22113322',
            rating: 4.8,
            reviewCount: 410,
            profileViews: 4500,
            featured: true,
            latitude: 12.9762,
            longitude: 77.6033,
            createdAt: new Date('2024-07-30').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            name: 'Delhi Public School, Bangalore North',
            logo: 'https://via.placeholder.com/150x150?text=DPS+Bangalore',
            bannerImage: 'https://via.placeholder.com/1200x400?text=DPS+Bangalore+Banner',
            address: 'Vidyaranyapura, Yelahanka',
            city: 'Bangalore',
            state: 'Karnataka',
            pincode: '560097',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Pre-KG to 12th',
            establishmentYear: 2002,
            studentTeacherRatio: '20:1',
            schoolType: 'Day School',
            feesMin: 52000,
            feesMax: 135000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Auditorium', 'Smart Classrooms', 'Cafeteria', 'Medical Room'],
            description: 'DPS Bangalore North offers quality CBSE education with modern facilities and experienced faculty. The school focuses on holistic development and preparing students for future challenges.',
            gallery: [
                'https://via.placeholder.com/800x600?text=DPS+BLR+Campus',
                'https://via.placeholder.com/800x600?text=DPS+BLR+Building',
                'https://via.placeholder.com/800x600?text=DPS+BLR+Lab',
                'https://via.placeholder.com/800x600?text=DPS+BLR+Sports'
            ],
            contactEmail: 'admissions@dpsbangalore.edu.in',
            contactPhone: '+91-80-28560000',
            rating: 4.4,
            reviewCount: 210,
            profileViews: 2800,
            featured: false,
            latitude: 13.1077,
            longitude: 77.5746,
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            name: 'Inventure Academy',
            logo: 'https://via.placeholder.com/150x150?text=Inventure',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Inventure+Banner',
            address: 'Whitefield-Sarjapur Road, Carmelaram Post',
            city: 'Bangalore',
            state: 'Karnataka',
            pincode: '560035',
            board: 'IB',
            medium: 'English',
            classesOffered: 'KG to 12th',
            establishmentYear: 2005,
            studentTeacherRatio: '15:1',
            schoolType: 'Both',
            feesMin: 65000,
            feesMax: 165000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Hostel', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Design Lab', 'Innovation Center'],
            description: 'Inventure Academy is a premier IB school that emphasizes innovation and entrepreneurship. The school provides an environment that nurtures critical thinking, creativity, and leadership skills.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Inventure+Campus',
                'https://via.placeholder.com/800x600?text=Inventure+Lab',
                'https://via.placeholder.com/800x600?text=Inventure+Sports',
                'https://via.placeholder.com/800x600?text=Inventure+Innovation',
                'https://via.placeholder.com/800x600?text=Inventure+Hostel',
                'https://via.placeholder.com/800x600?text=Inventure+Library'
            ],
            contactEmail: 'admissions@inventureacademy.edu.in',
            contactPhone: '+91-80-28450123',
            rating: 4.6,
            reviewCount: 240,
            profileViews: 3100,
            featured: false,
            latitude: 12.9257,
            longitude: 77.7465,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        // Pune Schools (3)
        {
            name: 'Gems International School, Pune',
            logo: 'https://via.placeholder.com/150x150?text=Gems+Pune',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Gems+Pune+Banner',
            address: 'Baner Road, Baner',
            city: 'Pune',
            state: 'Maharashtra',
            pincode: '411045',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 2012,
            studentTeacherRatio: '18:1',
            schoolType: 'Day School',
            feesMin: 48000,
            feesMax: 125000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Smart Classrooms', 'Cafeteria'],
            description: 'Gems International School Pune offers a world-class curriculum with focus on academic excellence and character development. The school provides a supportive environment for students to reach their full potential.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Gems+Campus',
                'https://via.placeholder.com/800x600?text=Gems+Building',
                'https://via.placeholder.com/800x600?text=Gems+Lab',
                'https://via.placeholder.com/800x600?text=Gems+Sports',
                'https://via.placeholder.com/800x600?text=Gems+Pool'
            ],
            contactEmail: 'admissions@gemspune.edu.in',
            contactPhone: '+91-20-27293000',
            rating: 4.5,
            reviewCount: 185,
            profileViews: 2500,
            featured: false,
            latitude: 18.5642,
            longitude: 73.7769,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'Podar International School, Kharadi',
            logo: 'https://via.placeholder.com/150x150?text=Podar+Kharadi',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Podar+Kharadi+Banner',
            address: 'EON Free Zone, Kharadi',
            city: 'Pune',
            state: 'Maharashtra',
            pincode: '411014',
            board: 'ICSE',
            medium: 'English',
            classesOffered: 'Pre-KG to 10th',
            establishmentYear: 2015,
            studentTeacherRatio: '20:1',
            schoolType: 'Day School',
            feesMin: 45000,
            feesMax: 115000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Smart Classrooms', 'Art Studio', 'Music Room', 'Cafeteria'],
            description: 'Podar Kharadi provides excellent ICSE education with modern teaching methods. The school focuses on nurturing creativity and critical thinking while maintaining strong academic standards.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Podar+Kharadi+Campus',
                'https://via.placeholder.com/800x600?text=Podar+Kharadi+Class',
                'https://via.placeholder.com/800x600?text=Podar+Kharadi+Lab',
                'https://via.placeholder.com/800x600?text=Podar+Kharadi+Sports'
            ],
            contactEmail: 'admissions@podarkharadi.edu.in',
            contactPhone: '+91-20-66839000',
            rating: 4.3,
            reviewCount: 155,
            profileViews: 1900,
            featured: false,
            latitude: 18.5532,
            longitude: 73.9486,
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            name: 'Symbiosis International School',
            logo: 'https://via.placeholder.com/150x150?text=Symbiosis',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Symbiosis+Banner',
            address: 'Viman Nagar',
            city: 'Pune',
            state: 'Maharashtra',
            pincode: '411014',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'KG to 12th',
            establishmentYear: 2003,
            studentTeacherRatio: '15:1',
            schoolType: 'Day School',
            feesMin: 55000,
            feesMax: 140000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Robotics Lab'],
            description: 'Symbiosis International School is known for its innovative approach to education and strong academic foundation. The school emphasizes global citizenship and prepares students for international standards.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Symbiosis+Campus',
                'https://via.placeholder.com/800x600?text=Symbiosis+Building',
                'https://via.placeholder.com/800x600?text=Symbiosis+Lab',
                'https://via.placeholder.com/800x600?text=Symbiosis+Sports',
                'https://via.placeholder.com/800x600?text=Symbiosis+Auditorium'
            ],
            contactEmail: 'admissions@symbiosis.edu.in',
            contactPhone: '+91-20-26602600',
            rating: 4.6,
            reviewCount: 265,
            profileViews: 3300,
            featured: true,
            latitude: 18.5679,
            longitude: 73.9143,
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        // Chennai Schools (3)
        {
            name: 'Delhi Public School, Velachery',
            logo: 'https://via.placeholder.com/150x150?text=DPS+Chennai',
            bannerImage: 'https://via.placeholder.com/1200x400?text=DPS+Chennai+Banner',
            address: 'Taramani Link Road, Velachery',
            city: 'Chennai',
            state: 'Tamil Nadu',
            pincode: '600042',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 2009,
            studentTeacherRatio: '20:1',
            schoolType: 'Day School',
            feesMin: 43000,
            feesMax: 110000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Auditorium', 'Smart Classrooms', 'Cafeteria', 'Medical Room'],
            description: 'DPS Velachery provides comprehensive CBSE education with focus on both academics and personality development. The school maintains high standards and has state-of-the-art infrastructure.',
            gallery: [
                'https://via.placeholder.com/800x600?text=DPS+Chennai+Campus',
                'https://via.placeholder.com/800x600?text=DPS+Chennai+Building',
                'https://via.placeholder.com/800x600?text=DPS+Chennai+Lab',
                'https://via.placeholder.com/800x600?text=DPS+Chennai+Sports'
            ],
            contactEmail: 'admissions@dpschennai.edu.in',
            contactPhone: '+91-44-42177000',
            rating: 4.4,
            reviewCount: 195,
            profileViews: 2600,
            featured: false,
            latitude: 12.9756,
            longitude: 80.2225,
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            name: 'Chettinad Vidyashram',
            logo: 'https://via.placeholder.com/150x150?text=Chettinad',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Chettinad+Banner',
            address: 'Rajiv Gandhi Salai, Padur',
            city: 'Chennai',
            state: 'Tamil Nadu',
            pincode: '603103',
            board: 'CBSE',
            medium: 'English',
            classesOffered: '1st to 12th',
            establishmentYear: 1986,
            studentTeacherRatio: '18:1',
            schoolType: 'Both',
            feesMin: 50000,
            feesMax: 130000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Hostel', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Smart Classrooms', 'Cafeteria'],
            description: 'Chettinad Vidyashram is one of Chennai\'s premier schools offering both day and boarding facilities. Known for its excellent academic record and holistic approach to education.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Chettinad+Campus',
                'https://via.placeholder.com/800x600?text=Chettinad+Building',
                'https://via.placeholder.com/800x600?text=Chettinad+Sports',
                'https://via.placeholder.com/800x600?text=Chettinad+Lab',
                'https://via.placeholder.com/800x600?text=Chettinad+Hostel'
            ],
            contactEmail: 'admissions@chettinadvidyashram.edu.in',
            contactPhone: '+91-44-27472244',
            rating: 4.5,
            reviewCount: 230,
            profileViews: 2900,
            featured: false,
            latitude: 12.8579,
            longitude: 80.2264,
            createdAt: new Date('2024-08-28').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            name: 'PS Senior Secondary School',
            logo: 'https://via.placeholder.com/150x150?text=PS+School',
            bannerImage: 'https://via.placeholder.com/1200x400?text=PS+School+Banner',
            address: 'Luz Church Road, Mylapore',
            city: 'Chennai',
            state: 'Tamil Nadu',
            pincode: '600004',
            board: 'State Board',
            medium: 'English',
            classesOffered: 'KG to 12th',
            establishmentYear: 1950,
            studentTeacherRatio: '25:1',
            schoolType: 'Day School',
            feesMin: 18000,
            feesMax: 55000,
            facilities: ['Library', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Smart Classrooms', 'Cafeteria'],
            description: 'PS Senior Secondary is a well-established institution offering State Board curriculum. The school is known for its affordable quality education and strong academic results.',
            gallery: [
                'https://via.placeholder.com/800x600?text=PS+Campus',
                'https://via.placeholder.com/800x600?text=PS+Classroom',
                'https://via.placeholder.com/800x600?text=PS+Lab',
                'https://via.placeholder.com/800x600?text=PS+Library'
            ],
            contactEmail: 'admissions@psschool.edu.in',
            contactPhone: '+91-44-24981234',
            rating: 4.1,
            reviewCount: 125,
            profileViews: 1600,
            featured: false,
            latitude: 13.0339,
            longitude: 80.2619,
            createdAt: new Date('2024-10-02').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        // Hyderabad Schools (2)
        {
            name: 'Oakridge International School',
            logo: 'https://via.placeholder.com/150x150?text=Oakridge',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Oakridge+Banner',
            address: 'Bachupally, Nizampet Road',
            city: 'Hyderabad',
            state: 'Telangana',
            pincode: '500090',
            board: 'IB',
            medium: 'English',
            classesOffered: 'Pre-KG to 12th',
            establishmentYear: 2007,
            studentTeacherRatio: '15:1',
            schoolType: 'Day School',
            feesMin: 70000,
            feesMax: 175000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Art Studio', 'Smart Classrooms', 'Innovation Lab', 'Robotics Lab'],
            description: 'Oakridge International is a premium IB school with world-class facilities and international curriculum. The school focuses on developing well-rounded students prepared for global challenges.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Oakridge+Campus',
                'https://via.placeholder.com/800x600?text=Oakridge+Building',
                'https://via.placeholder.com/800x600?text=Oakridge+Lab',
                'https://via.placeholder.com/800x600?text=Oakridge+Sports',
                'https://via.placeholder.com/800x600?text=Oakridge+Pool',
                'https://via.placeholder.com/800x600?text=Oakridge+Innovation'
            ],
            contactEmail: 'admissions@oakridge.edu.in',
            contactPhone: '+91-40-48649000',
            rating: 4.7,
            reviewCount: 285,
            profileViews: 3500,
            featured: true,
            latitude: 17.5110,
            longitude: 78.3656,
            createdAt: new Date('2024-08-22').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Chirec International School',
            logo: 'https://via.placeholder.com/150x150?text=Chirec',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Chirec+Banner',
            address: 'Kondapur, Gachibowli',
            city: 'Hyderabad',
            state: 'Telangana',
            pincode: '500084',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Nursery to 12th',
            establishmentYear: 2010,
            studentTeacherRatio: '18:1',
            schoolType: 'Day School',
            feesMin: 58000,
            feesMax: 145000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Swimming Pool', 'Transport', 'Playground', 'Auditorium', 'Music Room', 'Smart Classrooms', 'Cafeteria'],
            description: 'Chirec International School offers comprehensive CBSE education with emphasis on technology integration. The school provides a nurturing environment that encourages innovation and creativity.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Chirec+Campus',
                'https://via.placeholder.com/800x600?text=Chirec+Building',
                'https://via.placeholder.com/800x600?text=Chirec+Lab',
                'https://via.placeholder.com/800x600?text=Chirec+Sports'
            ],
            contactEmail: 'admissions@chirec.edu.in',
            contactPhone: '+91-40-40202000',
            rating: 4.5,
            reviewCount: 215,
            profileViews: 2700,
            featured: false,
            latitude: 17.4499,
            longitude: 78.3680,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        // Kolkata Schools (2)
        {
            name: 'Birla High School',
            logo: 'https://via.placeholder.com/150x150?text=Birla+High',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Birla+High+Banner',
            address: 'Shakespeare Sarani',
            city: 'Kolkata',
            state: 'West Bengal',
            pincode: '700017',
            board: 'ICSE',
            medium: 'English',
            classesOffered: '1st to 12th',
            establishmentYear: 1955,
            studentTeacherRatio: '20:1',
            schoolType: 'Day School',
            feesMin: 40000,
            feesMax: 105000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Auditorium', 'Smart Classrooms', 'Music Room', 'Art Studio'],
            description: 'Birla High School is one of Kolkata\'s most prestigious ICSE schools with a legacy of academic excellence. The school emphasizes value-based education and overall personality development.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Birla+Campus',
                'https://via.placeholder.com/800x600?text=Birla+Building',
                'https://via.placeholder.com/800x600?text=Birla+Lab',
                'https://via.placeholder.com/800x600?text=Birla+Sports',
                'https://via.placeholder.com/800x600?text=Birla+Library'
            ],
            contactEmail: 'admissions@birlahigh.edu.in',
            contactPhone: '+91-33-22821234',
            rating: 4.6,
            reviewCount: 305,
            profileViews: 3800,
            featured: false,
            latitude: 22.5509,
            longitude: 88.3522,
            createdAt: new Date('2024-08-08').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            name: 'Cambridge International School, Kolkata',
            logo: 'https://via.placeholder.com/150x150?text=Cambridge+KOL',
            bannerImage: 'https://via.placeholder.com/1200x400?text=Cambridge+KOL+Banner',
            address: 'E.M. Bypass, Anandapur',
            city: 'Kolkata',
            state: 'West Bengal',
            pincode: '700107',
            board: 'CBSE',
            medium: 'English',
            classesOffered: 'Pre-KG to 12th',
            establishmentYear: 2001,
            studentTeacherRatio: '18:1',
            schoolType: 'Day School',
            feesMin: 35000,
            feesMax: 95000,
            facilities: ['Library', 'Sports Complex', 'Science Lab', 'Computer Lab', 'Transport', 'Playground', 'Smart Classrooms', 'Auditorium', 'Cafeteria', 'Medical Room'],
            description: 'Cambridge International School provides quality CBSE education with modern facilities. The school focuses on creating a balanced learning environment that nurtures both academic and personal growth.',
            gallery: [
                'https://via.placeholder.com/800x600?text=Cambridge+Campus',
                'https://via.placeholder.com/800x600?text=Cambridge+Building',
                'https://via.placeholder.com/800x600?text=Cambridge+Lab',
                'https://via.placeholder.com/800x600?text=Cambridge+Sports'
            ],
            contactEmail: 'admissions@cambridgekolkata.edu.in',
            contactPhone: '+91-33-24423000',
            rating: 4.3,
            reviewCount: 165,
            profileViews: 2200,
            featured: false,
            latitude: 22.5119,
            longitude: 88.4077,
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
    ];

    await db.insert(schools).values(sampleSchools);
    
    console.log('✅ Schools seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});